[package]
name = "zigbee"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.0.27", features = ["derive"] }
futuresdr = { version = "0.0.34", features = ["zynq"] }
xilinx-dma = "0.0.7"
