[package]
name = "zigbee"
version = "0.0.1"
edition = "2021"

[dependencies]
futuresdr = { version = "0.0.31", features = ["zynq"], path = "/home/basti/src/futuresdr/" }
xilinx-dma = "0.0.7"

[patch.crates-io]
xilinx-dma = { path = "/home/basti/src/xilinx-dma/" }
